# Generated by Django 5.2.6 on 2025-10-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "voter_analytics",
            "0002_alter_voter_v20state_alter_voter_v21primary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="apt_number",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="street_name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="voter",
            name="street_number",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
