# Generated by Django 5.2.6 on 2025-10-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0003_voter_apt_number_voter_street_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="birth_year",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
