# Generated by Django 5.2.6 on 2025-10-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0004_voter_birth_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="score",
            field=models.TextField(),
        ),
    ]
