# Generated by Django 5.2.6 on 2025-10-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
