# Generated by Django 5.2.6 on 2025-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0005_photo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="join_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
