# Generated by Django 5.2.8 on 2025-12-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.player",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="box",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
