# Generated by Django 5.2.8 on 2025-12-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_player_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="coins",
        ),
        migrations.AddField(
            model_name="player",
            name="boxes_opened",
            field=models.IntegerField(default=0),
        ),
    ]
