# Generated by Django 5.2.8 on 2025-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_remove_player_coins_player_boxes_opened"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="tradee_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trade",
            name="trader_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
