# Generated by Django 5.2.8 on 2025-12-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_trade_tradee_confirmed_trade_trader_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="tradee_confirmed",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="trader_confirmed",
        ),
    ]
